### ISSUE TITLE
如何进入管理面板

### ISSUE THREAD

**Issue by Maxxiecook** [Cl0udG0d/QQFishing#2]
RT 建议 记录鱼IP

**Comment by Cl0udG0d** [comment]
访问 http://ip地址:5000/login 进行管理界面登录  
提示：默认管理员登录邮箱为:springbird@qq.com,密码为:springbird,登录之后请第一时间修改密码

**Comment by Cl0udG0d** [comment]
下一次更新的时候会增加记录目标IP的功能
