### ISSUE TITLE
测试了一下，不能防止恶意循环写入

### ISSUE THREAD

**Issue by mrcosir** [Cl0udG0d/QQFishing#3]
针对鱼雷，防止有人使用脚本恶意填充数据，使用IP检测进行恶意提交者的封禁

这个功能没有实现的，搭建测试了一下，后台重复许多！！

不过无所谓，主要是来学习大佬的flask技巧，找不到个感兴趣的项目，这个就不错。无聊学习学习！

**Comment by mrcosir** [comment]
对了，另外请教一下，这种是如何搭建在免费空间里的？有没有类似php空间那种搭建的。好像没有专门的flask空间！

**Comment by Cl0udG0d** [comment]
啊哈，鱼雷防止恶意提交的功能实际上还没有完成，如果自己在学习flask项目的话欢迎添加这个功能之后提交pull request哈；php空间我没有用过，但是项目直接搭建在服务器上面还是很方便的：)

**Comment by mrcosir** [comment]
> 啊哈，鱼雷防止恶意提交的功能实际上还没有完成，如果自己在学习flask项目的话欢迎添加这个功能之后提交pull requestha;php空间我没有用过，但是项目直接搭建在服务器上面还是很方便的：）

哎哟。居然还能实时回复，感谢感谢。不要服务器搭建可以么？例如注册一个免费空间那种，然后源代码放上去！

**Comment by Cl0udG0d** [comment]
莫事，因为刚好在用电脑hahah，关于免费空间我觉得是可以的，但是因为我没有用过，所以就不瞎指挥了😃

**Comment by mrcosir** [comment]
> 莫事，因为刚好在用电脑hahah，关于免费空间我觉得是可以的，但是因为我没有用过，所以就不瞎指挥了😃

好的，我慢慢学习。应该是只能服务器搭建。嘿嘿。

**Comment by Cl0udG0d** [comment]
嘿嘿，那我把这个 issue 关闭了，欢迎 pull 哈😜
