### ISSUE TITLE
额，关于后台以及MySQL的连接

### ISSUE THREAD

**Issue by tangzichengcc** [Cl0udG0d/QQFishing#4]
这个有后台可以查看钓鱼钓到的数据吗？mysql的话，账号密码是什么。在docker里怎么连接呢？

**Comment by Cl0udG0d** [comment]
可以的，我发现在readme里面没写后台地址hhh，后台地址的路由是 /login ，默认管理员登录邮箱为:springbird@qq.com,密码为:springbird
如果是使用docker部署的话，启动的时候就已经链接上了docker里面的mysql了，mysql密码是root，并且不允许外连，所以不需要担心密码被爆破的问题
😁

**Comment by Cl0udG0d** [comment]
![image](https://user-images.githubusercontent.com/45556496/146395641-3d90bd72-de79-4175-8b20-54aedb2c12a3.png)

**Comment by tangzichengcc** [comment]
要的要的，有就方便多了👍。我用的docker，刚开始不太熟悉，后来发现直接进mysql的docker也能查看。


谢谢解答！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月16日(周四) 晚上11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cl0udG0d/QQFishing] 额，关于后台以及MySQL的连接 (Issue #4)




 
可以的，我发现在readme里面没写后台地址hhh，后台地址的路由是 /login ***@***.***,密码为:springbird
 如果是使用docker部署的话，启动的时候就已经链接上了docker里面的mysql了，mysql密码是root，并且不允许外连，所以不需要担心密码被爆破的问题
 😁

**Comment by Cl0udG0d** [comment]
没事哈哈哈，熟能生巧，欢迎PR

**Comment by Cl0udG0d** [comment]
我把这个issue关闭了哈

**Comment by tangzichengcc** [comment]
嗯嗯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月16日(周四) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cl0udG0d/QQFishing] 额，关于后台以及MySQL的连接 (Issue #4)




 
我把这个issue关闭了哈
